### ISSUE TITLE
App crashing while starting UWB ranging in Pixel 6 PRO

### ISSUE THREAD

**Issue by dhilshad-tss** [nxp-uwb/UWBMobileKit#2]
Phone used: Pixel 6 PRO
Android version: 12
Google Play Service version: 23.24.14

Top most commit in this repo used: a375c680a7aff549125e54f7d79065a757335425

I am trying to run this app in Pixel 6 PRO with NXP SR150 as the peer device. in SR150 I have flashed the corresponding software and when I open the app it's connecting to SR150 device over Bluetooth. But when the SR150 reply with th configuration and App try to start UWB ranging app is crashing with error:
`java.lang.RuntimeException: Unexpected error. This indicates that the library is not up-to-date with the service backend.`

From the error message it looks like there is a mismatch between UWB jetpack library and the Google Play services.

From the android source code looks like this exception is thrown from an else case. So not very sure whether this error message is a misleading one or not.

Have you faced this issue already? Any idea how to go forward?

Complete error message:
I  Creating Gms Client session scope
E  FATAL EXCEPTION: Thread-2
   Process: com.jetpackexample, PID: 10533
   **java.lang.RuntimeException: Unexpected error. This indicates that the library is not up-to-date with the service backend.**
   	at androidx.core.uwb.helper.UwbHelperKt.handleApiException(UwbHelper.kt:52)
   	at androidx.core.uwb.impl.UwbManagerImpl.createGmsClientSessionScope(UwbManagerImpl.kt:110)
   	at androidx.core.uwb.impl.UwbManagerImpl.access$createGmsClientSessionScope(UwbManagerImpl.kt:41)
   	at androidx.core.uwb.impl.UwbManagerImpl$createGmsClientSessionScope$1.invokeSuspend(Unknown Source:15)
   	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
   	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
   	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
   	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
   	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
   	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
I  Removing dead content provider:android.content.ContentProviderProxy@e09192f

**Comment by jgeslin** [comment]
Hi,

From my side I'm able to run the apk on Pixel 6 PRO without any crash
 - Android 13
 - Google Play service version 23.24.14

Would you try Android 13 ?

Regards,
Jeremy.

**Comment by dhilshad-tss** [comment]
I am not having Android 13 update. 
Have you tried this application in Android 12 before?

**Comment by dhilshad-tss** [comment]
This issue is resolved after updating to Android 13.

These two are NOT available in Android 12. It is available in SDK 33 (ie, Android 13)
"androidx.core.uwb:uwb-rxjava3:1.0.0-alpha05"
"androidx.core.uwb:uwb:1.0.0-alpha05"

So this application will NOT work in Android 12. Better mention that as a prerequisite
